"""Change duration time to string

Revision ID: ef505e26f018
Revises: 70a3d5483572
Create Date: 2026-07-23 21:24:22.345410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef505e26f018'
down_revision = '70a3d5483572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=68),
               existing_nullable=True)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('news_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('video_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('video_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('news_link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.String(length=68),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
        batch_op.alter_column('surname',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
