"""Add Seen column to mesages

Revision ID: f55c1533f944
Revises: 9240c49ffc0c
Create Date: 2026-07-02 15:46:51.779498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55c1533f944'
down_revision = '9240c49ffc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rubric')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=False))

    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.alter_column('rubric_link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.alter_column('rubric_link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('seen')

    op.create_table('_alembic_tmp_rubric',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('img', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('duration', sa.TIME(), nullable=False),
    sa.Column('uploaded_at', sa.DATE(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rubric_link', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
